### ISSUE TITLE
Footer contents

### ISSUE THREAD

**Issue by bhantsi** [bhantsi/osca-opensource-challenge-2021#5]
In the footer section add the following contents:

- [x] copyright [OSCA KANO](https://twitter.com/osca_kano) [YEAR] for [Open Source Challenge](https://github.com/oscafrica/open-source-challenge-2021)
- [x] add social icon twitter for OSCA KANO and GitHub for oscafrica
## Design
Do as it pleases you but make sure the basic requirements are checked.

**Comment by kbhavre** [comment]
I will solve this issue.

**Comment by TemitopeAgbaje** [comment]
i can solve this issue

**Comment by bhantsi** [comment]
> I will solve this issue.

Hi, @kbhavre I can see that you already forked the repo but yet push your commit and make any PR, may I know what you are working on, or do you need any clarification or assistance?

**Comment by kbhavre** [comment]
Thankyou @bhantsi for your response , as I am new to open source I need some help to learn what I have to do after this

**Comment by bhantsi** [comment]
Hi @kbhavre all you have to do is work on the issue assign to you and make PR that's it.

**Comment by kbhavre** [comment]
Sorry 😞 @bhantsi i can't work on this issue

**Comment by bhantsi** [comment]
> Sorry  @bhantsi i can't work on this issue

Ok no problem, @TemitopeAgbaje I'm gonna assign it to you can go ahead
